"""create initial schema

Revision ID: 1468079925dd
Revises: dba076b43281
Create Date: 2025-04-07 01:42:04.230610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1468079925dd'
down_revision: Union[str, None] = 'dba076b43281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'organizer', ['id'])
    op.create_unique_constraint(None, 'organizer_to_hackathon', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizer_to_hackathon', type_='unique')
    op.drop_constraint(None, 'organizer', type_='unique')
    # ### end Alembic commands ###
