"""New migration

Revision ID: 4c428f64ec30
Revises: 9cdf03c7f189
Create Date: 2025-02-12 10:05:42.707013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c428f64ec30'
down_revision: Union[str, None] = '9cdf03c7f189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathons', sa.Column('img', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathons', 'img')
    # ### end Alembic commands ###
