"""create initial schema

Revision ID: 9141dcf460bc
Revises: 138ad08123d6
Create Date: 2025-04-07 01:13:07.147708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9141dcf460bc'
down_revision: Union[str, None] = '138ad08123d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'application', ['id'])
    op.create_unique_constraint(None, 'application_status', ['id'])
    op.create_unique_constraint(None, 'check_list', ['id'])
    op.create_unique_constraint(None, 'check_list_point', ['id'])
    op.create_unique_constraint(None, 'check_list_to_role', ['id'])
    op.create_unique_constraint(None, 'check_list_to_team_member', ['id'])
    op.create_unique_constraint(None, 'check_list_to_user', ['id'])
    op.create_unique_constraint(None, 'city', ['id'])
    op.add_column('hackathon', sa.Column('dates', sa.String(), nullable=True))
    op.add_column('hackathon', sa.Column('place', sa.String(), nullable=True))
    op.add_column('hackathon', sa.Column('organizers', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'hackathon', ['id'])
    op.create_unique_constraint(None, 'profile', ['id'])
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'team', ['id'])
    op.create_unique_constraint(None, 'team_member', ['id'])
    op.create_unique_constraint(None, 'tech_focus', ['id'])
    op.create_unique_constraint(None, 'tech_focus_to_hackathon', ['id'])
    op.create_unique_constraint(None, 'tech_focus_to_user', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'tech_focus_to_user', type_='unique')
    op.drop_constraint(None, 'tech_focus_to_hackathon', type_='unique')
    op.drop_constraint(None, 'tech_focus', type_='unique')
    op.drop_constraint(None, 'team_member', type_='unique')
    op.drop_constraint(None, 'team', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_constraint(None, 'hackathon', type_='unique')
    op.drop_column('hackathon', 'organizers')
    op.drop_column('hackathon', 'place')
    op.drop_column('hackathon', 'dates')
    op.drop_constraint(None, 'city', type_='unique')
    op.drop_constraint(None, 'check_list_to_user', type_='unique')
    op.drop_constraint(None, 'check_list_to_team_member', type_='unique')
    op.drop_constraint(None, 'check_list_to_role', type_='unique')
    op.drop_constraint(None, 'check_list_point', type_='unique')
    op.drop_constraint(None, 'check_list', type_='unique')
    op.drop_constraint(None, 'application_status', type_='unique')
    op.drop_constraint(None, 'application', type_='unique')
    # ### end Alembic commands ###
