"""create initial schema

Revision ID: dba076b43281
Revises: 9141dcf460bc
Create Date: 2025-04-07 01:18:18.315780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba076b43281'
down_revision: Union[str, None] = '9141dcf460bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('organizer_to_hackathon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.Column('hachathon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hachathon_id'], ['hackathon.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_column('hackathon', 'organizers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathon', sa.Column('organizers', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('organizer_to_hackathon')
    op.drop_table('organizer')
    # ### end Alembic commands ###
